site_name: ElseWhere
site_url: https://duetorun.com/
site_description: 在别处或在路上
site_author: Cliff Fan
copyright: Copyright &copy; 2024- Cliff Fan

repo_name: fan2/mkdocs
repo_url: https://github.com/fan2/mkdocs.git
# edit_uri: edit/main/docs/

# 指定主题
theme:
  name: material
  custom_dir: overrides
  language: zh
  favicon: assets/hold_yourself.jpg
  logo: assets/hold_yourself.jpg

  palette:
    # 跟随系统主题切换
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  features:
    # - toc.integrate # 右侧 TOC 集成到左侧 nav sidebar
    - toc.follow # TOC sidebar 跟随内容滚动定位
    - header.autohide # 向下滚动时自动隐藏header
    - navigation.tabs # 顶部显示导航顶层（nav第一级节点）
    # - navigation.tabs.sticky # 滚动时不隐藏顶部nav tab
    - navigation.top # 开启一键回到页面顶部按钮
    - navigation.footer # 开启底部上一篇/下一篇导航
    - navigation.tracking # 在url中使用标题定位锚点
    # Code Blocks
    - content.code.copy # Code Blocks 代码复制按钮
    - content.code.select # Code Block 行选择按钮
    - content.code.annotate # 折叠注释(隐藏/展开)

plugins:
  # enabled by default, but must be re-added when other plugins are used.
  - search
  # categorize any page with tags as part of the front matter of the page
  - tags
  - blog:
      blog_dir: blog
      # post_dir: posts
      post_excerpt: required
      # post_excerpt_separator: <!-- more -->
      blog_toc: true
      post_date_format: medium
      post_url_date_format: yyyyMMdd
      post_url_format: "{date}/{file}"
      pagination_per_page: 
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      # draft: true
      # draft_if_future_date: true
      archive_toc: true
      archive_name: xman 的归档
      archive_date_format: MMMM yyyy
      archive_url_date_format: yyyyMM
      archive_url_format: "archive/{date}"
      categories_toc: true
      categories_name: xman 的分类
      categories_url_format: "category/{slug}"

# includes by default: meta, toc, tables, fenced_code
markdown_extensions:
  ##############################
  # Officially Supported Extensions
  ## https://python-markdown.github.io/extensions/
  ## https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - toc:
      permalink: "#"
      separator: "_"
      # 参考 shafish.cn 和 jia.je，解决锚点无法显示中文问题
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - nl2br # cause newlines to be treated as hard breaks
  - sane_lists # do not allow the mixing of list types
  - footnotes
  - def_list # for Tasklist
  - attr_list # for Buttons, Images, Annotations, Card Grids
  - md_in_html # for Images, Annotations, Card Grids
  ##############################
  # Third Party Extensions
  ## https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions
  # pip install markdown-checklist
  # - markdown_checklist.extension

  ##############################
  # Material Natively Supported Extensions
  ## https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
  # Supersede markdown_checklist
  - pymdownx.tasklist:
      custom_checkbox: true
  # Content Tabs
  - pymdownx.tabbed:
      alternate_style: true
  # Formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  # Code Blocks
  - pymdownx.superfences # Supersede fenced_code
  - pymdownx.highlight: # Supersede fenced_codecodehilite
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets  # embed external files
  # Admonition
  - admonition
  - pymdownx.details
  # MathJax
  - pymdownx.arithmatex:
      generic: true
  # Icons, Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  # MathJax
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # busuanzi statistics
  - https://vercount.one/js

extra:
  analytics:
    provider: google
    property: G-XGW41EGL31

# 编译忽略
# exclude_docs: |
#   drafts/

# 页面导航
nav:
  - About: about.md
  - Blog: blog/index.md
  - Link: link.md
