site_name: 逃跑计划
site_url: https://duetorun.com/

# 指定主题
theme:
  name: material
  favicon: assets/hold_yourself.jpg
  logo: assets/hold_yourself.jpg

  palette:
    # 跟随系统主题切换
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

# includes by default: meta, toc, tables, fenced_code
markdown_extensions:
  ##############################
  # Python Markdown Extensions
  - toc:
      permalink: "#"
      separator: "_"
  # cause newlines to be treated as hard breaks
  - nl2br
  # do not allow the mixing of list types
  - sane_lists
  - footnotes
  ##############################
  # Third Party Extensions
  # pip install markdown-checklist
  - markdown_checklist.extension

# 编译忽略
exclude_docs: |
  drafts/

# 页面导航
nav:
  - Home: index.md
  - Mkdocs:
    - First Glance: mkdocs/first_glance.md
    - Getting Started: mkdocs/getting_started.md
    - Customizing Theme: mkdocs/customizing_theme.md
    - Configuration: mkdocs/configuration.md
    - Deployment: mkdocs/deployment.md
    - Markdown:
      - Markdown Extensions: mkdocs/markdown_extensions.md
    - Material:
      - Material Guide: mkdocs/material_guide.md
      - Material Appearance: mkdocs/material_appearance.md
  - About: about.md
